.TH SWORDFISH 1 "April 14, 2009"
.SH NAME
swordfish \- high-level persistent key-value database
.SH SYNOPSIS
.B sworfish
.SH DESCRIPTION
Swordfish is a key-value database for primarily storing and processing sorted
sets (or "trees"). It is intended to supplement a relational database such as
MySQL.
.PP
It can be interfaced from any language with a HTTP client.
.SH OPTIONS
.IP "configfile"
Read options from specified configuration file.
.SH AUTHOR
\fBswordfish\fP was written by Chris Lamb <chris@playfire.com>.
