#!/bin/sh

. ./_testcase

GET /databases/${DB}/trees/one
Assert '{"items": []}'

GET /databases/${DB}/trees/two
Assert '{"items": []}'

# Intersection

GET /databases/${DB}/trees/one/intersection/two
Assert '{"items": []}'

GET /databases/${DB}/trees/one/intersection/two\?values=all
Assert '{"items": []}'

GET /databases/${DB}/trees/one/intersection/two\?values=keys
Assert '{"items": []}'

GET /databases/${DB}/trees/one/intersection/two\?values=values
Assert '{"items": []}'

# Counts

GET /databases/${DB}/trees/one/intersection/two/count
Assert '{"count": 0}'
