#!/bin/sh

. _testcase

POST /database/${DB}/trees/one/item/aaa a-value

GET /database/${DB}/trees/one
Assert '{"items": [["aaa","a-value"]]}'

# Map

! POST /database/${DB}/trees/one/map/tree-/key value

GET /database/${DB}/trees/tree-
Assert '{"items": []}'

POST /database/${DB}/trees/one/map/tree-%%/key value

GET /database/${DB}/trees/tree-aaa%
Assert '{"items": [["key","value"]]}'
