#!/bin/sh

. ./_testcase

POST /databases/${DB}/trees/one/item/aaa a-value
POST /databases/${DB}/trees/one/item/bbb b-value
POST /databases/${DB}/trees/one/item/ccc c-value

POST /databases/${DB}/trees/two/item/bbb b-value
POST /databases/${DB}/trees/two/item/ccc c-value
POST /databases/${DB}/trees/two/item/ddd d-value

GET /databases/${DB}/trees/one
Assert '{"items": [["aaa","a-value"],["bbb","b-value"],["ccc","c-value"]]}'

GET /databases/${DB}/trees/two
Assert '{"items": [["bbb","b-value"],["ccc","c-value"],["ddd","d-value"]]}'

# Intersection

GET /databases/${DB}/trees/one/intersection/two
Assert '{"items": [["bbb","b-value"],["ccc","c-value"]]}'

GET /databases/${DB}/trees/one/intersection/two\?values=all
Assert '{"items": [["bbb","b-value"],["ccc","c-value"]]}'

GET /databases/${DB}/trees/one/intersection/two\?values=keys
Assert '{"items": ["bbb","ccc"]}'

GET /databases/${DB}/trees/one/intersection/two\?values=values
Assert '{"items": ["b-value","c-value"]}'

# Counts

GET /databases/${DB}/trees/one/intersection/two/count
Assert '{"count": 2}'
