#!/bin/sh

. _testcase

GET /database/${DB}/trees/one
Assert '{"items": []}'

GET /database/${DB}/trees/two
Assert '{"items": []}'

# Intersection

GET /database/${DB}/trees/one/intersection/two
Assert '{"items": []}'

GET /database/${DB}/trees/one/intersection/two\?values=all
Assert '{"items": []}'

GET /database/${DB}/trees/one/intersection/two\?values=keys
Assert '{"items": []}'

GET /database/${DB}/trees/one/intersection/two\?values=values
Assert '{"items": []}'

# Counts

GET /database/${DB}/trees/one/intersection/two/count
Assert '{"count": 0}'
