#!/bin/sh

. _testcase

POST /database/${DB}/trees/one/item/aaa a-value
POST /database/${DB}/trees/one/item/bbb b-value
POST /database/${DB}/trees/one/item/ccc c-value

GET /database/${DB}/trees/one
Assert '{"items": [["aaa","a-value"],["bbb","b-value"],["ccc","c-value"]]}'

GET /database/${DB}/trees/tree-aaa
Assert '{"items": []}'

GET /database/${DB}/trees/tree-bbb
Assert '{"items": []}'

GET /database/${DB}/trees/tree-ccc
Assert '{"items": []}'

# Map

POST /database/${DB}/trees/one/map/tree-%/key value

GET /database/${DB}/trees/tree-aaa
Assert '{"items": [["key","value"]]}'

GET /database/${DB}/trees/tree-bbb
Assert '{"items": [["key","value"]]}'

GET /database/${DB}/trees/tree-ccc
Assert '{"items": [["key","value"]]}'

# Check "map delete"

POST /database/${DB}/trees/one/item/ddd d-value

GET /database/${DB}/trees/one
Assert '{"items": [["aaa","a-value"],["bbb","b-value"],["ccc","c-value"],["ddd","d-value"]]}'

POST /database/${DB}/trees/one/map/tree-%/key

GET /database/${DB}/trees/tree-aaa
Assert '{"items": []}'

GET /database/${DB}/trees/tree-bbb
Assert '{"items": []}'

GET /database/${DB}/trees/tree-ccc
Assert '{"items": []}'

GET /database/${DB}/trees/tree-ddd
Assert '{"items": []}'
