#!/bin/sh

. ./_testcase

! GET /databases/${DB}/trees/treename/item/aaa

POST /databases/${DB}/trees/treename/item/aaa "value"

GET /databases/${DB}/trees/treename
Assert '{"items": [["aaa","value"]]}'

GET /databases/${DB}/trees/treename/count
Assert '{"count": 1}'

POST /databases/${DB}/trees/treename/item/unknown ""

GET /databases/${DB}/trees/treename/count
Assert '{"count": 1}'

POST /databases/${DB}/trees/treename/item/aaa ""

! GET /databases/${DB}/trees/treename/item/aaa

GET /databases/${DB}/trees/treename
Assert '{"items": []}'

GET /databases/${DB}/trees/treename/count
Assert '{"count": 0}'
