#!/bin/sh

. ./_testcase

POST /databases/${DB}/trees/one/item/aaa a-value

GET /databases/${DB}/trees/one
Assert '{"items": [["aaa","a-value"]]}'

# Map

! POST /databases/${DB}/trees/one/map/tree-/key value

GET /databases/${DB}/trees/tree-
Assert '{"items": []}'

POST /databases/${DB}/trees/one/map/tree-%%/key value

GET /databases/${DB}/trees/tree-aaa%
Assert '{"items": [["key","value"]]}'
