#!/bin/sh

. _testcase

POST /databases/${DB}/trees/treename/item/zzz z-value
GET /databases/${DB}/trees/treename/item/zzz
Assert '{"item": "z-value"}'

# Check items

GET /databases/${DB}/trees/treename
Assert '{"items": [["zzz","z-value"]]}'

GET /databases/${DB}/trees/treename\?values=all
Assert '{"items": [["zzz","z-value"]]}'

GET /databases/${DB}/trees/treename\?values=keys
Assert '{"items": ["zzz"]}'

GET /databases/${DB}/trees/treename\?values=values
Assert '{"items": ["z-value"]}'

# Check counts

GET /databases/${DB}/trees/treename/count
Assert '{"count": 1}'

GET /databases/${DB}/trees/treename/count\?values=all
Assert '{"count": 1}'

GET /databases/${DB}/trees/treename/count\?values=keys
Assert '{"count": 1}'

GET /databases/${DB}/trees/treename/count\?values=keys
Assert '{"count": 1}'

# Overwrite value

POST /databases/${DB}/trees/treename/item/zzz new-value

GET /databases/${DB}/trees/treename
Assert '{"items": [["zzz","new-value"]]}'
