#!/bin/sh

. _testcase

POST /database/${DB}/trees/one/item/aaa a-value
POST /database/${DB}/trees/one/item/bbb b-value
POST /database/${DB}/trees/one/item/ccc c-value

GET /database/${DB}/trees/one
Assert '{"items": [["aaa","a-value"],["bbb","b-value"],["ccc","c-value"]]}'

GET /database/${DB}/trees/two
Assert '{"items": []}'

# Difference

GET /database/${DB}/trees/one/difference/two
Assert '{"items": [["aaa","a-value"],["bbb","b-value"],["ccc","c-value"]]}'

GET /database/${DB}/trees/one/difference/two\?values=all
Assert '{"items": [["aaa","a-value"],["bbb","b-value"],["ccc","c-value"]]}'

GET /database/${DB}/trees/one/difference/two\?values=keys
Assert '{"items": ["aaa","bbb","ccc"]}'

GET /database/${DB}/trees/one/difference/two\?values=values
Assert '{"items": ["a-value","b-value","c-value"]}'

# Counts

GET /database/${DB}/trees/one/difference/two/count
Assert '{"count": 3}'
