#!/bin/sh

. _testcase

POST /databases/${DB}/trees/one/item/aaa a-value
POST /databases/${DB}/trees/one/item/bbb b-value
POST /databases/${DB}/trees/one/item/ccc c-value

GET /databases/${DB}/trees/one
Assert '{"items": [["aaa","a-value"],["bbb","b-value"],["ccc","c-value"]]}'

GET /databases/${DB}/trees/tree-aaa
Assert '{"items": []}'

GET /databases/${DB}/trees/tree-bbb
Assert '{"items": []}'

GET /databases/${DB}/trees/tree-ccc
Assert '{"items": []}'

# Map

POST /databases/${DB}/trees/one/map/tree-%/key value

GET /databases/${DB}/trees/tree-aaa
Assert '{"items": [["key","value"]]}'

GET /databases/${DB}/trees/tree-bbb
Assert '{"items": [["key","value"]]}'

GET /databases/${DB}/trees/tree-ccc
Assert '{"items": [["key","value"]]}'
