#!/bin/sh

. _testcase

POST /databases/${DB}/trees/one/item/aaa a-value
POST /databases/${DB}/trees/one/item/bbb b-value
POST /databases/${DB}/trees/one/item/ccc c-value

POST /databases/${DB}/trees/two/item/bbb b-value
POST /databases/${DB}/trees/two/item/ccc c-value
POST /databases/${DB}/trees/two/item/ddd d-value

GET /databases/${DB}/trees/one
Assert '{"items": [["aaa","a-value"],["bbb","b-value"],["ccc","c-value"]]}'

GET /databases/${DB}/trees/two
Assert '{"items": [["bbb","b-value"],["ccc","c-value"],["ddd","d-value"]]}'

# Difference

GET /databases/${DB}/trees/one/difference/two
Assert '{"items": [["aaa","a-value"]]}'

GET /databases/${DB}/trees/one/difference/two\?values=all
Assert '{"items": [["aaa","a-value"]]}'

GET /databases/${DB}/trees/one/difference/two\?values=keys
Assert '{"items": ["aaa"]}'

GET /databases/${DB}/trees/one/difference/two\?values=values
Assert '{"items": ["a-value"]}'

# Counts

GET /databases/${DB}/trees/one/difference/two/count
Assert '{"count": 1}'
