#!/bin/sh

. _testcase

GET /database/${DB}/trees/one
Assert '{"items": []}'

GET /database/${DB}/trees/two
Assert '{"items": []}'

# Difference

GET /database/${DB}/trees/one/difference/two
Assert '{"items": []}'

GET /database/${DB}/trees/one/difference/two\?values=all
Assert '{"items": []}'

GET /database/${DB}/trees/one/difference/two\?values=keys
Assert '{"items": []}'

GET /database/${DB}/trees/one/difference/two\?values=values
Assert '{"items": []}'

# Counts

GET /database/${DB}/trees/one/difference/two/count
Assert '{"count": 0}'
