#!/bin/sh

. _testcase

POST /database/${DB}/trees/two/item/bbb b-value
POST /database/${DB}/trees/two/item/ccc c-value
POST /database/${DB}/trees/two/item/ddd d-value

GET /database/${DB}/trees/one
Assert '{"items": []}'

GET /database/${DB}/trees/two
Assert '{"items": [["bbb","b-value"],["ccc","c-value"],["ddd","d-value"]]}'

# Intersection

GET /database/${DB}/trees/one/intersection/two
Assert '{"items": []}'

GET /database/${DB}/trees/one/intersection/two\?values=all
Assert '{"items": []}'

GET /database/${DB}/trees/one/intersection/two\?values=keys
Assert '{"items": []}'

GET /database/${DB}/trees/one/intersection/two\?values=values
Assert '{"items": []}'

# Counts

GET /database/${DB}/trees/one/intersection/two/count
Assert '{"count": 0}'
