#!/bin/sh

. ./_testcase

POST /databases/${DB}/trees/two/item/bbb b-value
POST /databases/${DB}/trees/two/item/ccc c-value
POST /databases/${DB}/trees/two/item/ddd d-value

GET /databases/${DB}/trees/one
Assert '{"items": []}'

GET /databases/${DB}/trees/two
Assert '{"items": [["bbb","b-value"],["ccc","c-value"],["ddd","d-value"]]}'

# Difference

GET /databases/${DB}/trees/one/difference/two
Assert '{"items": []}'

GET /databases/${DB}/trees/one/difference/two\?values=all
Assert '{"items": []}'

GET /databases/${DB}/trees/one/difference/two\?values=keys
Assert '{"items": []}'

GET /databases/${DB}/trees/one/difference/two\?values=values
Assert '{"items": []}'

# Counts

GET /databases/${DB}/trees/one/difference/two/count
Assert '{"count": 0}'
